export const CLIENTE_SERVICE = 'CLIENTE_SERVICE';
export const CUENTA_SERVICE = 'CUENTA_SERVICE';
export const MOVIMIENTO_SERVICE = 'MOVIMIENTO_SERVICE';
export const REPORTE_SERVICE = 'REPORTE_SERVICE';
